GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/devops_starter_war_exploded/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}


###
GET http://localhost:8080/devops_starter_war_exploded/api/hobby

###
PUT http://localhost:8080/devops_starter_war_exploded/api/hobby/Akrobatik

{"name": "Akrobatik", "description": "this should be link to wiki", "category": "Generel", "type": "Indendørs", "people": {"1":"Jens Jensen", "2": "Mads Madsen"}}

###
GET http://localhost:8080/devops_starter_war_exploded/api/person

